### ISSUE TITLE
Fatal error: stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by corbanb** [hypermurea/generator-phonegap#10]
Any ideas why on an initial setup when I run `$ grunt platform-build` I am getting the error **Fatal error: stdout maxBuffer exceeded.**?

Environment Info: OSX 10.9.2

```
npm - 1.4.3
node - 0.10.26
yo -1.1.2
phonegap - 3.4.0-0.19.8
grunt-cli - 0.1.13
grunt - 0.4.4
```

**Comment by xdemocle** [comment]
Please, do you know any solutions?

**Comment by hypermurea** [comment]
In your Gruntfile.js you can set phonegap.config.maxBuffer to a reasonably big value, say maxBuffer: 500 

This issue usually comes up when you build iOS apps, its mentioned in grunt-phonegap docs. Hope this helps

**Comment by xdemocle** [comment]
Hi hypermurea,
many thanks for your help.
I didn't find anything online, I thought that was related to my environment and not to phonegap configs.
