### ISSUE TITLE
Issue running phonegap generator on Windows

### ISSUE THREAD

**Issue by dalanmiller** [hypermurea/generator-phonegap#5]
@marcoscmu experienced this issue.

For some reason when running `yo` and then selecting the phonegap generator, it errors out at this screen. 

![image](https://f.cloud.github.com/assets/863286/1519903/4ef5114c-4b6f-11e3-82fb-e079662cd9d2.png)

**Comment by sanat** [comment]
I have the same issue.

**Comment by vjsai** [comment]
Even i have the same issue

**Comment by hypermurea** [comment]
Tried to replicate this error: Correct me, but I assume you have first installed yo with 'npm install -g yo', and then you are using the command-line utility by running 'yo', then searching for phonegap in the generator list, and the following install fails? I tried and I am unable to replicate the problem (windows 8), could you send me log dump from the command line so I can replicate this in the same way.

**Comment by sanat** [comment]
Yes that is correct. Here is the log from running 'yo'. This is on windows 8

Yeoman is a mask worn by the following members of the open-source community:

  Paul Irish, Addy Osmani, Mickael Daniel, Sindre Sorhus, Eric Bidelman,
  Frederick Ros, Brian Ford, Pascal Hartig, Stephen Sawchuk, and countless
  other contributors.

[?] What would you like to do? Run the Phonegap generator (0.1.1)

Before you create a new application, be sure you are in the directory you
wish your application to be dropped into.

You may also run the following command to initiate this generator:

```
yo phonegap


 _-----_
|       |
|--(o)--|   .--------------------------.
```

   `---------´  |    Welcome to Yeoman,    |
    ( _´U`_ )   |   ladies and gentlemen!  |
    /**_A**_\   '__________________________'
     |  ~  |
   **'._**.'__
 ´   `|° ´ Y`

[?] What is the name of your PhoneGap project? Hello World
[?] What is your application package: [A[B[C[D[B
[?] What platform builds would you like? Android
   create Gruntfile.js
   create package.json
   create .gitignore
   create .gitattributes
   create .bowerrc
   create bower.json
   create .jshintrc
   create .editorconfig
   create app/styles/main.css
   create app/index.html
   create app/scripts/index.js
   create Initialized PhoneGap project

Bye from us! Chat soon.

```
        Addy Osmani
      Sindre Sorhus
    Brian Ford
 Eric Bidelman
          Paul Irish
 Mickael Daniel
      Pasca1 Hartig
  Stephen S.wchuk
Frederick R0s
```

C:\Users\Sanat\AppData\Roaming\npm\node_modules\generator-phonegap\node_modules\extended-fs\src\fs.js:417
            throw new TypeError(src + ' does not exist');
                  ^
TypeError: G:\Dropbox\sanatwamp\www\testing-yo\phonegap\www\res does not exist
    at Object.fsExtended.copyDirSync (C:\Users\Sanat\AppData\Roaming\npm\node_modules\generator-phonegap\node_modules\ex
tended-fs\src\fs.js:417:19)
    at PhonegapGenerator.phonegapSetup (C:\Users\Sanat\AppData\Roaming\npm\node_modules\generator-phonegap\app\index.js:
193:8)
    at C:\Users\Sanat\AppData\Roaming\npm\node_modules\generator-phonegap\node_modules\yeoman-generator\lib\base.js:290:
20
    at C:\Users\Sanat\AppData\Roaming\npm\node_modules\generator-phonegap\node_modules\yeoman-generator\node_modules\asy
nc\lib\async.js:548:21
    at C:\Users\Sanat\AppData\Roaming\npm\node_modules\generator-phonegap\node_modules\yeoman-generator\node_modules\asy
nc\lib\async.js:224:13
    at iterate (C:\Users\Sanat\AppData\Roaming\npm\node_modules\generator-phonegap\node_modules\yeoman-generator\node_mo
dules\async\lib\async.js:131:13)
    at C:\Users\Sanat\AppData\Roaming\npm\node_modules\generator-phonegap\node_modules\yeoman-generator\node_modules\asy
nc\lib\async.js:142:25
    at C:\Users\Sanat\AppData\Roaming\npm\node_modules\generator-phonegap\node_modules\yeoman-generator\node_modules\asy
nc\lib\async.js:226:17
    at C:\Users\Sanat\AppData\Roaming\npm\node_modules\generator-phonegap\node_modules\yeoman-generator\node_modules\asy
nc\lib\async.js:553:34
    at C:\Users\Sanat\AppData\Roaming\npm\node_modules\generator-phonegap\node_modules\yeoman-generator\lib\base.js:278:
11
PS G:\Dropbox\sanatwamp\www\testing-yo>

I've made sure that extended-fs is installed

**Comment by hypermurea** [comment]
I've updated the generator, if you can verify that the issue has been resolved, if there are still problems I'll look into it more.

**Comment by sanat** [comment]
Yes that worked. Thanks @hypermurea
